groups:
  - name: spring-boot-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_server_requests_seconds_count{status=~"5.."}[1m]) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Tax error 5xx too high"
          description: "More than 50% of the requests on the last 1 minute return error 5xx."

      - alert: InstanceDown
        expr: up{job="spring-boot-app"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Spring Boot instance is down."
          description: "One of the instances of the application is not responding."

      - alert: CircuitBreakerTripped
        expr: rate(http_server_requests_seconds_count{status="503"}[1m]) > 0.2
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Circuit Breaker frequently activated."
          description: "The application is respondig with status 503 frequently, this means internal server issues."