services:
  spring-server-1:
    container_name: spring-server-1
    build:
      context: .
    environment:
      - SERVER_NAME=Server_1
    ports:
      - "8081:8080"
    networks:
      - app_network

  spring-server-2:
    container_name: spring-server-2
    build:
      context: .
    environment:
      - SERVER_NAME=Server_2
    ports:
      - "8082:8080"
    networks:
      - app_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - spring-server-1
      - spring-server-2
    volumes:
      - ./nginx/logs:/var/log/nginx
    networks:
      - app_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - app_network
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./alertManager/alerts.yaml:/etc/prometheus/alerts.yaml
      - prometheus_data:/prometheus

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - app_network
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    networks:
      - app_network
    ports:
    - "9093:9093"
    volumes:
    - ./alertManager/alertManager.yaml:/etc/alertmanager/alertmanager.yml

  promtail:
    container_name: promtail
    build:
      context: ./promtail
    networks:
      - app_network
    ports:
      - "9094:9094"
    volumes:
      - ./nginx/logs:/var/log/nginx
    
  loki:
    container_name: loki
    build:
      context: ./loki
    networks:
      - app_network
    ports:
      - "3100:3100"
    volumes:
      - ./loki:/loki
      - loki_data:/var/loki
    depends_on:
      - promtail

networks:
  app_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
